version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "02:00"
      timezone: "Asia/Tokyo"
    target-branch: "develop"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "02:30"
      timezone: "Asia/Tokyo"
    target-branch: "develop"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
