minimumReleaseAge: 4320

overrides:
  "rollup@>=4.0.0 <4.22.4": ">=4.22.4"
  "minimatch@<3.1.4": "3.1.4"
  "minimatch@>=9.0.0 <9.0.7": ">=9.0.7"
  "cross-spawn@>=7.0.0 <7.0.5": ">=7.0.5"
  "glob@>=10.2.0 <10.5.0": ">=10.5.0"
  "flatted@<3.4.0": ">=3.4.0"
  "picomatch@<2.3.2": ">=2.3.2"
  "esbuild@<0.25.0": ">=0.25.0"
  "@babel/runtime@<7.26.10": ">=7.26.10"
  "micromatch@<4.0.8": ">=4.0.8"
  "yaml@>=2.0.0 <2.8.3": ">=2.8.3"
  "brace-expansion@>=2.0.0 <2.0.3": ">=2.0.3"
  "nanoid@<3.3.8": ">=3.3.8"
  "js-yaml@>=4.0.0 <4.1.1": ">=4.1.1"
