#!/bin/sh

print_help()
{
  echo "\tstg\tステージングビルド"
  echo "\tprod\tプロダクションビルド"
  echo "\tall\tりょうほう"
  echo "\tなし\tりょうほう"
  echo "\n\thelp\tこれです"
  exit 0
}

build_prod(){
  rm -rf release/kanColleWidget
  mkdir release/kanColleWidget
  cp -r src release/kanColleWidget/
  mv release/kanColleWidget/src/img/icon* release/kanColleWidget/
  cp manifest.json release/kanColleWidget/
  zip -r release/kanColleWidget.zip release/kanColleWidget/*
}

build_stg(){
  rm -rf release/stg.kanColleWidget
  mkdir release/stg.kanColleWidget
  cp -r src release/stg.kanColleWidget/
  mv release/stg.kanColleWidget/src/img/icon* release/stg.kanColleWidget/
  cp manifest.stg.json release/stg.kanColleWidget/manifest.json
  zip -r release/stg.kanColleWidget.zip release/stg.kanColleWidget/*
}

build_all(){
  build_prod
  build_stg
}

show_manifest_diff(){
  echo "\nstgパッケージとのdiffを表示"
  diff --recursive release/kanColleWidget release/stg.kanColleWidget
}

get_ver_in_manifest(){
  echo `grep version manifest.json | grep -v manifest_version | tr -d " "`
}
get_ver_in_config(){
  echo `grep version src/html/config.html | sed -e 's/<[^>]*>//g' | sed -e 's/ver//' | tr -d " "`
}
get_ver_in_more(){
  echo `grep version src/html/more.html   | sed -e 's/<[^>]*>//g' | tr -d " "`
}
version_check(){
  echo "\nバージョン情報のチェック"
  echo "manifest.json\t"`get_ver_in_manifest`
  echo "config.html\t"`get_ver_in_config`
  echo "more.html\t"`get_ver_in_more`
}

if [ $# -lt 1 ]; then
  build_all
  show_manifest_diff
  version_check
fi

case $1 in
  "prod" )
    build_prod
    break;;
  "stg" )
    build_stg
    break;;
  "all" )
    build_prod
    build_stg
    show_manifest_diff
    version_check
    break;;
  "help" )
    print_help
    break;;
  * )
esac
